const actionTypes = Object.freeze({
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  APP_START_UP_FALSE: "APP_START_UP_FALSE",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
});

export default actionTypes;
